#server:
#  port: 8000

payment:
  kafka:
    message-group-name: notification-group-test

    payment-executed-topic: hw35.payment.executed-test
    payment-rejected-topic: hw35.payment.rejected-test

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/db_otus_35
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092